Project-Complete/Complete_BE

- settings.gradle
- src/main/java/org/complete/challang/ChallangApplication.java
- src/main/java/org/complete/challang/test/TestController.java
- src/test/java/org/complete/challang/ChallangApplicationTests.java
> chore: 프로젝트 아티팩트 변경

- src/main/java/org/complete/challang/account/user/domain/entity/DrinkBookmark.java
- src/main/java/org/complete/challang/account/user/domain/entity/DrinkLike.java
- src/main/java/org/complete/challang/account/user/domain/entity/SocialType.java
- src/main/java/org/complete/challang/account/user/domain/entity/User.java
- src/main/java/org/complete/challang/common/domain/entity/BaseEntity.java
- src/main/java/org/complete/challang/drink/domain/entity/Drink.java
- src/main/java/org/complete/challang/drink/domain/entity/DrinkDetailType.java
- src/main/java/org/complete/challang/drink/domain/entity/DrinkFood.java
- src/main/java/org/complete/challang/drink/domain/entity/DrinkManufacturer.java
- src/main/java/org/complete/challang/drink/domain/entity/DrinkPackage.java
- src/main/java/org/complete/challang/drink/domain/entity/DrinkTag.java
- src/main/java/org/complete/challang/drink/domain/entity/DrinkType.java
- src/main/java/org/complete/challang/drink/domain/entity/Food.java
- src/main/java/org/complete/challang/drink/domain/entity/FoodStatistic.java
- src/main/java/org/complete/challang/drink/domain/entity/Location.java
- src/main/java/org/complete/challang/drink/domain/entity/Package.java
- src/main/java/org/complete/challang/drink/domain/entity/SituationStatistic.java
- src/main/java/org/complete/challang/drink/domain/entity/Tag.java
- src/main/java/org/complete/challang/drink/domain/entity/TasteStatistic.java
- src/main/java/org/complete/challang/review/domain/entity/Flavor.java
- src/main/java/org/complete/challang/review/domain/entity/Review.java
- src/main/java/org/complete/challang/review/domain/entity/ReviewFlavor.java
- src/main/java/org/complete/challang/review/domain/entity/ReviewFood.java
- src/main/java/org/complete/challang/review/domain/entity/Situation.java
- src/main/java/org/complete/challang/review/domain/entity/Taste.java
- BaseEntity class 생성
- BaseEntity class를 상속한 각 entity 구현
- 연관관계 매핑
closed #7
> feat: 도메인 구현

- build.gradle
- src/main/java/org/complete/challang/common/config/SwaggerConfig.java
> chore: Swagger 전역 설정

- .github/workflows/dev-actions.yml
- GithubActions develop 브랜치 PR시 workflow 동작 제거
closed #13
> chore: Github Actions Script 변경

- src/main/java/org/complete/challang/drink/domain/repository/DrinkQueryRepositoryImpl.java
- src/main/java/org/complete/challang/drink/service/DrinkService.java
- Lazy loading proxy 조회 이슈 해결 (by Transcation)
- only full group by 해결 (group by 절에 특정 컬럼을 추가)
closed #30
> hotfix: 주류 상세기능 오류 수정

- src/main/java/org/complete/challang/drink/controller/dto/response/DrinkTypeFindResponse.java
- src/main/java/org/complete/challang/drink/controller/dto/response/FlavorStatisticFindResponse.java
- src/main/java/org/complete/challang/drink/controller/dto/response/FoodStatisticFindResponse.java
- src/main/java/org/complete/challang/drink/controller/dto/response/ManufacturerFindResponse.java
- src/main/java/org/complete/challang/drink/controller/dto/response/PackageFindResponse.java
- src/main/java/org/complete/challang/drink/controller/dto/response/TagFindResponse.java
- src/main/java/org/complete/challang/drink/controller/dto/response/TasteAverageStatistic.java
- src/main/java/org/complete/challang/drink/domain/entity/SituationStatistic.java
- 주류 상세조회 DTO 안의 객체에 스네이크 케이스 반환 설정 적용
closed #32
> refactor: DrinkFindResponse내 SnakeCase 적용

- .github/workflows/dev-actions.yml
- Dockerfile
- src/main/resources/application-dev.yml
- src/main/resources/application-jwt.yml
- src/main/resources/application-oauth.yml
- src/main/resources/application.yml
- Dockerhub 연동 및 Dockerfile 작성
- Application.yml 값을 Github Secrets에서 받음
- Docker 관련 스크립트 작성
- self-hosted runner 활용
closed #28
> chore: Github Actions Docker 적용

- build.gradle
- src/main/java/org/complete/challang/account/jwt/Token.java
- src/main/java/org/complete/challang/account/jwt/filter/TokenAuthenticationFilter.java
- src/main/java/org/complete/challang/account/user/domain/repository/UserRepository.java
- src/main/java/org/complete/challang/common/domain/entity/BaseEntity.java
- src/main/java/org/complete/challang/common/exception/ErrorCode.java
- src/main/java/org/complete/challang/drink/domain/entity/Drink.java
- src/main/java/org/complete/challang/drink/domain/entity/SituationStatistic.java
- src/main/java/org/complete/challang/drink/domain/entity/TasteStatistic.java
- src/main/java/org/complete/challang/drink/domain/repository/DrinkRepository.java
- src/main/java/org/complete/challang/review/controller/ReviewController.java
- src/main/java/org/complete/challang/review/controller/dto/item/ReviewDto.java
- src/main/java/org/complete/challang/review/controller/dto/item/WriterDto.java
- src/main/java/org/complete/challang/review/controller/dto/response/ReviewDetailResponse.java
- src/main/java/org/complete/challang/review/domain/entity/Review.java
- src/main/java/org/complete/challang/review/domain/entity/ReviewSortCriteria.java
- src/main/java/org/complete/challang/review/domain/repository/ReviewRepository.java
- src/main/java/org/complete/challang/review/service/ReviewService.java
- src/test/java/org/complete/challang/app/review/controller/ReviewControllerTest.java
- src/test/java/org/complete/challang/app/review/service/ReviewServiceTest.java
- JWT getPayload 함수 관련 에러 수정
- spring-security-test 의존성 추가
- 권한이 필요한 API contextHolder에 저장된 UserDetail을 활용하여 사용자 정보 추가
- 주류 리뷰 삭제 기능을 soft delete로 구현
closed #17 #18 #36 #38
> feat: 주류 리뷰 삭제 API 구현 및 생성, 조회 API 수정

- src/main/java/org/complete/challang/drink/controller/DrinkController.java
- src/main/java/org/complete/challang/drink/controller/dto/response/DrinkListFindResponse.java
- src/main/java/org/complete/challang/drink/domain/entity/criteria/DrinkTypeCriteria.java
- src/main/java/org/complete/challang/drink/domain/repository/DrinkRepository.java
- src/main/java/org/complete/challang/drink/service/DrinkService.java
- 타입별 및 좋아요순 주류 리스트 조회 기능
- JPQL로 좋아요 순위 및 타입 필터 정렬
closed #21
> feat: 주류 추천 리스트 조회 기능 구현

- .github/workflows/dev-actions.yml
- src/main/java/org/complete/challang/account/jwt/filter/TokenAuthenticationFilter.java
- src/main/java/org/complete/challang/account/oauth2/handler/OAuth2SuccessHandler.java
- src/main/java/org/complete/challang/account/oauth2/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
- src/main/java/org/complete/challang/account/oauth2/util/CookieUtils.java
- src/main/java/org/complete/challang/common/exception/ErrorCode.java
- src/main/java/org/complete/challang/config/SecurityConfig.java
- src/main/java/org/complete/challang/handler/CustomAccessDeniedHandler.java
- src/main/java/org/complete/challang/handler/CustomAuthenticationEntryPoint.java
- src/main/resources/application-oauth.yml
- src/main/resources/application.yml
- OAuth2 로그인 성공시 프론트에서 지정해준 redirect url 쿼리스트링으로 반환
- 인증 및 인가 실패시 AuthenticationEntryPoint, AccessDeniedHandler 적용
- Github Actions 워크플로우 secret 수정 (callback url, cors permit url)
closed #40 #48
> feat: OAuth2 로그인 Redirect URL 반환 및 인증, 인가 Handler 적용

- build.gradle
- src/main/java/org/complete/challang/account/user/controller/UserController.java
- src/main/java/org/complete/challang/account/user/controller/dto/response/UserProfileFindResponse.java
- src/main/java/org/complete/challang/account/user/domain/entity/User.java
- src/main/java/org/complete/challang/account/user/service/UserService.java
- src/main/java/org/complete/challang/config/QueryDSLConfig.java
- src/main/java/org/complete/challang/review/controller/ReviewController.java
- src/main/java/org/complete/challang/review/domain/repository/ReviewCustomRepository.java
- src/main/java/org/complete/challang/review/domain/repository/ReviewCustomRepositoryImpl.java
- src/main/java/org/complete/challang/review/service/ReviewService.java
- QueryDSL 의존성 추가
- 주류 리뷰 리스트 검색 기능 QueryDSL로 리펙토링 및 검색 옵션에 작성자 추가
- 사용자 프로필 검색 get api 추가
closed #42
> feat: 주류 리뷰 목록 조회 검색 옵션 생성

- src/main/java/org/complete/challang/account/jwt/Token.java
- src/main/java/org/complete/challang/account/jwt/filter/TokenAuthenticationFilter.java
- src/main/java/org/complete/challang/account/oauth2/handler/OAuth2FailureHandler.java
- src/main/java/org/complete/challang/account/oauth2/handler/OAuth2SuccessHandler.java
- src/main/java/org/complete/challang/common/exception/ErrorCode.java
- src/main/java/org/complete/challang/common/exception/ErrorResponse.java
- src/main/java/org/complete/challang/common/exception/FilterErrorResponse.java
- src/main/java/org/complete/challang/common/exception/GlobalExceptionHandler.java
- src/main/java/org/complete/challang/handler/CustomAccessDeniedHandler.java
- src/main/java/org/complete/challang/handler/CustomAuthenticationEntryPoint.java
- src/main/resources/application.yml
- Controller 예외를 잡지못해 발생한 착오 해결
- 원본 Exception message도 함께 표기
- UserDetails에 authorities 부여 (authenticated = true)
closed #56
> fix: 상세한 Exception 처리를 통한 bug 수정

- .github/workflows/dev-actions.yml
- build.gradle
- src/main/java/org/complete/challang/common/controller/S3Controller.java
- src/main/java/org/complete/challang/common/controller/dto/request/PreSignedUrlGetRequest.java
- src/main/java/org/complete/challang/common/controller/dto/response/PreSignedUrlGetResponse.java
- src/main/java/org/complete/challang/common/exception/ErrorCode.java
- src/main/java/org/complete/challang/common/service/S3Service.java
- src/main/java/org/complete/challang/config/S3Config.java
- src/main/java/org/complete/challang/config/SecurityConfig.java
- src/main/resources/application-cloud.yml
- src/main/resources/application.yml
- 프론트 단에서 DTO로 넘겨준 fileName으로 유효성 검사
- pre-signed url 주소 10분간 유효
closed #29
> feat: S3 pre-signed url 요청 기능 구현

- src/main/java/org/complete/challang/account/user/controller/UserController.java
- src/main/java/org/complete/challang/account/user/controller/dto/common/FollowDto.java
- src/main/java/org/complete/challang/account/user/controller/dto/response/FollowsFindResponse.java
- src/main/java/org/complete/challang/account/user/controller/dto/response/UserProfileFindResponse.java
- src/main/java/org/complete/challang/account/user/domain/entity/Follow.java
- src/main/java/org/complete/challang/account/user/domain/entity/User.java
- src/main/java/org/complete/challang/account/user/domain/repository/FollowRepository.java
- src/main/java/org/complete/challang/account/user/service/UserService.java
- src/main/java/org/complete/challang/common/exception/ErrorCode.java
- src/main/java/org/complete/challang/common/exception/SuccessCode.java
- src/main/java/org/complete/challang/review/domain/entity/Review.java
- src/main/java/org/complete/challang/review/domain/repository/ReviewRepository.java
- 팔로우 기능 구현
- 팔로우 취소 기능 구현
- 팔로우 목록 조회 기능 구현
closed #55
> 팔로우 관련 기능 개발

- src/main/java/org/complete/challang/account/oauth2/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
- src/main/java/org/complete/challang/common/exception/GlobalExceptionHandler.java
- src/main/java/org/complete/challang/drink/domain/entity/criteria/DrinkSortCriteria.java
- src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepository.java
- src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepositoryImpl.java
- src/main/java/org/complete/challang/drink/domain/repository/DrinkRepository.java
- src/main/java/org/complete/challang/drink/service/DrinkService.java
- 기존 인기순 조회 JPQL 로직 미사용
- 새 QueryDSL 로직으로 변경
closed #45
> feat: 주류 타입별 리스트 조회 구현

- src/main/java/org/complete/challang/account/user/domain/entity/DrinkLike.java
- src/main/java/org/complete/challang/common/exception/ErrorCode.java
- src/main/java/org/complete/challang/common/exception/SuccessCode.java
- src/main/java/org/complete/challang/drink/controller/DrinkController.java
- src/main/java/org/complete/challang/drink/domain/entity/Drink.java
- src/main/java/org/complete/challang/drink/service/DrinkService.java
- 주류 좋아요 추가 기능 구현
- 주류 좋아요 삭제 기능 구현
closed #59
> feat: 주류 좋아요 로직 구현

- src/main/java/org/complete/challang/drink/controller/DrinkController.java
- src/main/java/org/complete/challang/drink/controller/dto/response/DrinkFindResponse.java
- src/main/java/org/complete/challang/drink/controller/dto/response/DrinkListFindResponse.java
- src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepository.java
- src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepositoryImpl.java
- src/main/java/org/complete/challang/drink/domain/repository/DrinkRepository.java
- src/main/java/org/complete/challang/drink/service/DrinkService.java
- src/test/java/org/complete/challang/drink/controller/DrinkControllerTest.java
- src/test/java/org/complete/challang/drink/service/DrinkServiceTest.java
- 주류 단건 조회시 좋아요 여부
- 주류 추천 조회시 좋아요 여부
- 주류 타입별 조회시 좋아요 여부
closed #51
> feat: 주류 관련 조회시 좋아요 여부 구현

- src/main/java/org/complete/challang/common/controller/S3Controller.java
- pre-signed url 요청은 페이로드를 포함해야하므로 Post 메서드로 변경
closed #73
> fix: pre-signed url 요청 POST로 변경

- src/main/java/org/complete/challang/account/user/controller/UserController.java
- src/main/java/org/complete/challang/review/controller/ReviewController.java
- 각 컨트롤러의 도메인 및 설명 작성
- 각 API의 기능 요약 및 상세 설명 작성
closed #69
> comment: 각 API swagger 주석 추가

- src/main/java/org/complete/challang/common/controller/S3Controller.java
- src/main/java/org/complete/challang/drink/controller/DrinkController.java
- 주류 컨트롤러 API 설명 작성
- S3 컨트롤러 API 설명 작성
closed #69
> comment: 주류 및 pre-signed url 관련 Swagger 수정

- src/main/java/org/complete/challang/config/QueryDSLConfig.java
- src/main/java/org/complete/challang/drink/controller/DrinkController.java
- src/main/java/org/complete/challang/drink/controller/dto/response/DrinkBannerListFindResponse.java
- src/main/java/org/complete/challang/drink/controller/dto/response/FoodStatisticFindResponse.java
- src/main/java/org/complete/challang/drink/controller/dto/response/ManufacturerFindResponse.java
- src/main/java/org/complete/challang/drink/domain/entity/criteria/DrinkSortCriteria.java
- src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepository.java
- src/main/java/org/complete/challang/drink/domain/repository/DrinkCustomRepositoryImpl.java
- src/main/java/org/complete/challang/drink/service/DrinkService.java
- QueryDSL의 transform을 이용한 DTO 매핑
- 추천 기준이 미정이므로 random으로 선정
closed #75
> feat: 메인배너 추천 주류리스트 기능 구현

- src/main/java/org/complete/challang/app/account/user/controller/UserController.java
- src/main/java/org/complete/challang/app/account/user/service/UserService.java
- src/main/java/org/complete/challang/app/common/controller/MainController.java
- src/main/java/org/complete/challang/app/common/controller/dto/response/SearchListFindResponse.java
- src/main/java/org/complete/challang/app/common/repository/MainCustomRepository.java
- src/main/java/org/complete/challang/app/common/repository/MainCustomRepositoryImpl.java
- src/main/java/org/complete/challang/app/common/service/MainService.java
- src/main/java/org/complete/challang/app/drink/controller/dto/response/DrinkPageResponse.java
- src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCustomRepository.java
- src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCustomRepositoryImpl.java
- src/main/java/org/complete/challang/app/util/QueryUtils.java
- src/main/java/org/complete/challang/config/SecurityConfig.java
- QueryDSL 이용하여 쿼리 구성
- 평균평점 로직 분리 (QueryUtils)
- url 접근권한 수정 (/main/**)
closed #46, #82
> feat: 좋아요 주류 및 통합검색 기능 추가

- src/main/java/org/complete/challang/config/SwaggerConfig.java
- Swagger http 주소로 인한 CORS 에러 해결
- 배포 개발 주소 및 로컬 주소 반영
closed #90
> fix: Swagger 요청 Server URL error 수정

- src/main/java/org/complete/challang/app/account/user/controller/UserController.java
- src/main/java/org/complete/challang/app/review/controller/ReviewController.java
- src/main/java/org/complete/challang/app/review/controller/dto/item/ReviewDto.java
- src/main/java/org/complete/challang/app/review/controller/dto/response/ReviewDetailResponse.java
- src/main/java/org/complete/challang/app/review/service/ReviewService.java
- 주류 리뷰 목록 조회 API에 query param 추가 API 개발
- 주류 리뷰 목록 함수 기능 수정
closed #94
> feat: 주류 리뷰 조회 관련 API 수정

- src/main/java/org/complete/challang/app/common/service/S3Service.java
- presigend url의 만료시간을 기존 30분에서 30초로 조정
closed #87
> refactor: Presigned url duration 조정

- src/main/java/org/complete/challang/app/account/user/controller/UserController.java
-  사용자 자신의 프로필을 조회하기 위해 url 추가
closed #97
> feat: findUserProfile API url 추가

- src/main/java/org/complete/challang/app/drink/controller/dto/response/DrinkBannerListFindResponse.java
- src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCustomRepositoryImpl.java
- 메인 배너 situation(상황별, 같이 마시면 좋은 사람) 정보 반환
- 기존 Like status는 불필요하기에 반영 철회
closed #101
> feat: 메인 배너 조회 Situation(같이 마시면 좋은 사람) 반환

- src/main/java/org/complete/challang/app/account/user/controller/UserController.java
- src/main/java/org/complete/challang/app/account/user/service/UserService.java
- UserController 좋아요 주류 목록 조회 Handler 메서드에 Query 파라미터 추가 (size, page)
- UserService 좋아요 주류 목록조회 비즈니스 로직 파라미터 추가 (size, page)
closed #104
> refactor: 좋아요 주류 목록 조회 리팩토링

- src/main/java/org/complete/challang/app/review/controller/dto/item/DrinkDto.java
- src/main/java/org/complete/challang/app/review/controller/dto/item/ReviewDto.java
- src/main/java/org/complete/challang/app/review/controller/dto/response/ReviewListFindResponse.java
-  리뷰 목록 조회 시 리뷰 한 주류의 ID, 이름을 반환하도록 기능 수정
closed #106
> feat: 리뷰 목록 조회 API 수정

- src/main/java/org/complete/challang/app/account/user/controller/UserController.java
- src/main/java/org/complete/challang/app/account/user/controller/dto/response/FollowCheckResponse.java
- src/main/java/org/complete/challang/app/account/user/service/UserService.java
-  사용자 팔로우 유무를 확인 가능한 API 개발
closed #105
> feat: 사용자 팔로우 유무 API 개발

- build.gradle
- src/main/java/org/complete/challang/ChallangApplication.java
- src/main/java/org/complete/challang/app/aop/LoggingAspect.java
- src/main/java/org/complete/challang/app/common/exception/GlobalExceptionHandler.java
- src/main/resources/console-appender.xml
- src/main/resources/discord-appender.xml
- src/main/resources/logback-spring.xml
- 서버 에러 발생시 Error Log를 Discord로 전송
- 성공한 요청에 대해 부가적인 정보를 Logging Aspect를 통해 적용
resolved #113
> feat: Error 발생시 Discord Webhook 및 Logging AOP 적용

- src/main/java/org/complete/challang/annotation/IdValid.java
- src/main/java/org/complete/challang/app/account/user/controller/UserController.java
- src/main/java/org/complete/challang/app/common/controller/MainController.java
- src/main/java/org/complete/challang/app/common/controller/S3Controller.java
- src/main/java/org/complete/challang/app/common/controller/dto/request/PreSignedUrlFindRequest.java
- src/main/java/org/complete/challang/app/common/exception/ErrorCode.java
- src/main/java/org/complete/challang/app/common/exception/ErrorResponse.java
- src/main/java/org/complete/challang/app/common/exception/GlobalExceptionHandler.java
- src/main/java/org/complete/challang/app/drink/controller/DrinkController.java
- src/main/java/org/complete/challang/app/drink/controller/dto/item/DrinkTypeDto.java
- src/main/java/org/complete/challang/app/drink/controller/dto/item/ManufacturerDto.java
- src/main/java/org/complete/challang/app/drink/controller/dto/item/PackageDto.java
- src/main/java/org/complete/challang/app/drink/controller/dto/request/DrinkCreateRequest.java
- ID Validation을 위한 Custom annotaion 구성
- Handler Method에 필요한 Annotation 추가
- Validation Error 관련 ErrorResponse 추가
- Validation Exception Handling 추가
closed #112
> feat: 주류 관련 API Validation 적용

- src/main/java/org/complete/challang/app/combination/controller/CombinationController.java
- src/main/java/org/complete/challang/app/combination/controller/dto/item/CombinationCreateUpdateDto.java
- src/main/java/org/complete/challang/app/combination/controller/dto/request/CombinationBoardCreateRequest.java
- src/main/java/org/complete/challang/app/combination/controller/dto/request/CombinationBoardUpdateRequest.java
- src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardCreateUpdateResponse.java
- src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardListFindResponse.java
- src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardPageResponse.java
- src/main/java/org/complete/challang/app/combination/domain/entity/Combination.java
- src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoard.java
- src/main/java/org/complete/challang/app/combination/domain/entity/CombinationSortCriteria.java
- src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepository.java
- src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
- src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardRepository.java
- src/main/java/org/complete/challang/app/combination/repository/CombinationBoardRepository.java
- src/main/java/org/complete/challang/app/combination/service/CombinationService.java
- src/main/java/org/complete/challang/app/common/exception/ErrorCode.java
- src/main/java/org/complete/challang/app/common/exception/SuccessCode.java
- src/main/java/org/complete/challang/app/drink/domain/entity/criteria/DrinkSortCriteria.java
- 주류 조합 게시글 리스트 조회 기능 구현
- QueryDSL 코드로 코드 로직 작성
- 주류 조합 게시글 수정 기능 구현
- Combination 과의 연관관계를 Set 자료구조를 통해 create/update 
- 주류 조합 게시글 삭제 기능 구현
closed #120
> feat: 주류 조합 게시글 리스트 조회, 수정, 삭제 구현

- src/main/java/org/complete/challang/app/combination/controller/CombinationController.java
- src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardFindResponse.java
- src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationBoardListFindResponse.java
- src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoard.java
- src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoardBookmark.java
- src/main/java/org/complete/challang/app/combination/domain/entity/CombinationBoardLike.java
- src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
- src/main/java/org/complete/challang/app/combination/service/CombinationService.java
- src/main/java/org/complete/challang/app/common/exception/ErrorCode.java
- src/main/java/org/complete/challang/app/common/exception/SuccessCode.java
- CombinationBoardLike, CombinationBoardBookmark entity 추가
- CombinationBoard에 좋아요/북마크 엔터티 로직 추가
- 주류 조합 좋아요/북마크 비즈니스 로직 및 API 추가 
- 주류 조합 상세조회 좋아요/북마크 여부 및 count 반환 리팩토링
- 주류 조합 리스트조회 좋아요/북마크 여부 반환 리팩토링  
closed #128
> feat: 주류 조합 게시글 좋아요/북마크 기능 구현

- src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationCommentResponse.java
- src/main/resources/application-dev.yml
- 주류조합 댓글/답글 조회시 profileImage 반환
- Response DTO 수정 
close #134
> refactor: 주류조합 댓글 조회시 유저 이미지 반환

- src/main/java/org/complete/challang/app/combination/controller/CombinationCommentController.java
- src/main/java/org/complete/challang/app/combination/controller/dto/response/CombinationCommentResponse.java
- src/main/java/org/complete/challang/app/combination/domain/entity/CombinationComment.java
- src/main/java/org/complete/challang/app/combination/service/CombinationCommentService.java
- src/main/java/org/complete/challang/app/common/exception/SuccessCode.java
- src/main/java/org/complete/challang/app/common/exception/SuccessResponse.java
- 주류조합 댓글 Delete 기능 구현 (hard delete)
closed #131
> feat: 주류 조합 댓글 삭제 기능 구현

- src/main/java/org/complete/challang/app/combination/domain/entity/CombinationSortCriteria.java
- src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
- src/main/java/org/complete/challang/app/combination/service/CombinationBoardService.java
- src/main/java/org/complete/challang/app/common/exception/ErrorResponse.java
- src/main/java/org/complete/challang/app/common/exception/SuccessCode.java
- src/main/java/org/complete/challang/app/drink/domain/entity/criteria/DrinkSortCriteria.java
- src/main/java/org/complete/challang/app/drink/domain/repository/DrinkCustomRepositoryImpl.java
- 주류 조합 리스트 조회 정렬 기준 (인기순) 추가
- 좋아요, 북마크 기준 
- 주류 리스트 조회 정렬 기준 (리뷰순) 추가
- Soft delete로 처리된 주류 조합 조회시 Error throw
closed #132 #135
> feature: 주류 조합 정렬 기준 추가 및 삭제 주류조합 조회시 error 처리

- src/main/java/org/complete/challang/app/review/service/ReviewService.java
> style: 코딩 컨벤션수정

- src/main/java/org/complete/challang/app/account/user/controller/UserController.java
- src/main/java/org/complete/challang/app/account/user/service/UserService.java
- src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepository.java
- src/main/java/org/complete/challang/app/combination/domain/repository/CombinationBoardCustomRepositoryImpl.java
- 특정 유저가 작성한 주류 조합 리스트 조회
- 특정 유저가 좋아요한 주류 조합 리스트 조회
- 특정 유저가 북마크한 주류 조합 리스트 조회
closed #144
> feat: 특정 User 관련 주류 조합 리스트 조회 기능 구현
